### ISSUE TITLE
Infinite loop on int validation

### ISSUE THREAD

**Issue by hs2600** [Art-Stea1th/Tic-tac-toe#1]
When the game starts and asks for a number between 1 and 3 and I enter a letter, it goes into an infinite error loop.
Eg.
Enter X (1-3): a
Input Err: Out of range
Enter X (1-3): 
Input Err: Out of range
etc.

![image](https://cloud.githubusercontent.com/assets/12635326/11739933/faf3b4fa-9fa3-11e5-8f66-08a616be5732.png)

**Comment by Art-Stea1th** [comment]
Thank you for taking the error ;) Fixed.
https://github.com/Art-Stea1th/Tic-tac-toe/commit/d2d5e8de70d05f9abdc504ed5509c2545b40b823

It works, but I have not yet come up with a better solution :\
